require 'opt.options'
require 'opt.keymaps'
require 'opt.plugins'
require 'opt.colorschemes'
require 'opt.cmp'
require 'opt.lsp'
require 'opt.telescope'
require 'opt.treesitter'
require 'opt.lualine'
require 'opt.autopairs'
require 'opt.nvim-tree'

